version: "2"

formatters:
  enable:
    # - gofumpt
    # - goimports

  settings:
    gofmt:
      # simplify code: gofmt with `-s` option, true by default
      simplify: true

    goimports:
      # put imports beginning with prefix after 3rd-party packages;
      # it's a comma-separated list of prefixes
      local-prefixes:
        - go.opentelemetry.io/collector

linters:
  enable-all: true
  disable:
    # Disabled because of
    #   - too many non-sensical warnings
    #   - not relevant for us
    #   - false positives

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - sloppyReassign
      - uncheckedInlineErr # Experimental rule with high false positive rate.

      # Broken with Go 1.18 feature (https://github.com/golangci/golangci-lint/issues/2649):
      - hugeParam
      - rangeValCopy
      - typeDefFirst
      - paramTypeCombine
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - debug,debugf,debugln
          - error,errorf,errorln
          - fatal,fatalf,fataln
          - info,infof,infoln
          - log,logf,logln
          - warn,warnf,warnln
          - print,printf,println,sprint,sprintf,sprintln,fprint,fprintf,fprintln
  lll:
    line-length: 120
    tab-width: 4
  maligned:
    suggest-new: true
  misspell:
    locale: US
